name: WorldCreatorPlugin
version: 1.0
main: com.example.WorldCreatorPlugin
commands:
  world:
    description: Creates a new world
    usage: /<command> create <name>
    permission: worldcreator.admin
    permission-message: "You do not have permission to use this command."
  listworlds:
    description: Lists all worlds
    usage: /<command>
    permission: worldcreator.admin
    permission-message: "You do not have permission to use this command."
permissions:
  worldcreator.admin:
    description: "Allows the player to create worlds and list worlds"
    default: op
